---
title: "Exemplo mínimo doctr"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
library(dplyr)
library(stringr)
library(magrittr)
library(readr)
library(tibble)
library(purrr)
```

Para instalar

```{r, message=FALSE}
devtools::install_local("/home/caio/doctr/")
library(doctr)
```

Base exemplo

```{r, message=FALSE, include=FALSE}
X <- tibble(
  dinheiro = c(
    1.23, 12.00, 1.5, 12.23, NA, NA
  ),
  contagem = c(
    1, 2, 3, 4, 5, 6
  ),
  quantidade = c(
    13.1415, 1234567.12, 1.111, 12, 13, NA
  ),
  continua = c(
    -123.1234, -2, 0, NA, NA, 12345
  ),
  categorica = c(
    "oi", "oi", "tchau", NA, "oi", "asdf"
  )
)
```

```{r, echo=FALSE}
knitr::kable(X, digits = 1)
```

Gerar análise exploratória de X

```{r}
X %>%
  examine() %>%
  summary_dbl() %>%
  knitr::kable(digits = 1)
X %>%
  examine() %>%
  summary_chr() %>%
  knitr::kable(digits = 1)
```

Gerar análise exploratória de X agrupada

```{r}
X %>%
  examine("categorica") %>%
  summary_dbl("oi") %>%
  knitr::kable(digits = 1)
X %>%
  examine(5) %>%
  summary_dbl("tchau") %>%
  knitr::kable(digits = 1)
```

Exames exemplo

```{r, message=FALSE, include=FALSE}
X <- tibble(
  dinheiro = c(
    1.23, 12.00, 1.5, 12.23, NA, NA
  ),
  contagem = c(
    1, 2, 3, 4, 5, 6
  ),
  quantidade = c(
    13.1415, 1234567.12, 1.111, 12, 13, NA
  ),
  continua = c(
    -123.1234, -2, 0, NA, NA, 12345
  ),
  categorica = c(
    "oi", "oi", "tchau", NA, "oi", "asdf"
  )
)
```

```{r, echo=FALSE}
exams <- tibble(
  cols = c(
    "dinheiro", "contagem", "quantidade", "continua", "categorica"
  ),
  funs = c(
    "money", "count", "quantity", "continuous", "categorical"
  ),
  max_na = c(
    "0.25", "", "", "0", "0"
  ),
  min_val = c(
    "", "5", "", "", ""
  ),
  max_val = c(
    "", "", "15", "", ""
  ),
  max_dec_places = c(
    "", "", "", "3", ""
  ),
  min_unq = c(
    "", "", "", "", "5"
  ),
  max_unq = c(
    "", "", "", "", "2"
  ),
  least_frec_cls = c(
    "", "", "", "", "0.5"
  )
)
```

Rodar exames e pegar resultados

```{r}
X %>%
  diagnose(exams) %>%
  issues()
X %>%
  diagnose(exams) %>%
  issues(3)
X %>%
  diagnose(exams) %>%
  issues("categorica")
```

Comparar X a outras tabelas

```{r}
X %>%
  compare(X) %>%
  issues()
X %>%
  compare(exams) %>%
  issues()
X %>%
  compare(X[1:5, ]) %>%
  issues(4)
```










